jaqpot_ui/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from jaqpot_ui import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='home'),
                       url(r'^login/?next=/$', views.login),
                       url(r'^login', views.login),
                       url(r'^logout', views.logout),
                       url(r'^task', views.task),
                       url(r'^t_detail', views.taskdetail),
                       url(r'^bibtex_delete', views.bib_delete),
                       url(r'^bibtex', views.bibtex),
                       url(r'^bib_detail', views.bib_detail),
                       url(r'^add_bibtex', views.add_bibtex),
                       url(r'^bibtex_delete', views.bib_delete),
                       url(r'^substance', views.all_substance),
                       url(r'^sub', views.sub),
                       url(r'^user', views.user),
                       url(r'^error', views.error),
                       url(r'^train', views.trainmodel),
                       url(r'^dataset', views.choose_dataset),
                       url(r'^data_detail', views.dataset_detail),
                       url(r'^d_delete', views.dataset_delete),
                       url(r'^predicted_dataset', views.dispay_predicted_dataset),
                       url(r'^data', views.dataset),
                       url(r'^algorithm_delete', views.algorithm_delete),
                       url(r'^algorithm_detail', views.algorithm_detail),
                       url(r'^algorithm', views.algorithm),
                       url(r'^conformer', views.conformer),
                       url(r'^model', views.model),
                       url(r'^m_delete', views.model_delete),
                       url(r'^m_detail', views.model_detail),
                       url(r'^m_pmml', views.model_pmml),
                       url(r'^feature_delete', views.feature_delete),
                       url(r'^feature_detail', views.feature_details),
                       url(r'^features', views.features),
                       url(r'^addfeature', views.add_feature),
                       url(r'^predict_model', views.predict_model),
                       url(r'^predict', views.predict),
                       url(r'^contact', views.contact),
                       url(r'^thanks', views.thanks),
                       url(r'^compound_detail', views.compound_details),
                       url(r'^compound', views.compound),
                       url(r'^source', views.source),
                       url(r'^documentation', views.documentation),
                       url(r'^explore', views.explore),
                       url(r'^stoptask', views.stop_task),
                       url(r'^change_params', views.change_params),
                       url(r'^select_substance', views.select_substance),
                       url(r'^get_substance', views.get_substance),
                       url(r'^properties', views.select_properties),
                       url(r'^descriptors', views.select_descriptors),
                       url(r'^calculate_image_descriptors', views.calculate_image_descriptors),
                       url(r'^calculate_mopac_descriptors', views.calculate_mopac_descriptors),
                       url(r'^validate', views.validate),
                       url(r'^valid_params', views.valid_params),
                       url(r'^external_validation', views.external_validation),
                       url(r'^ext_valid_model', views.ext_valid_model),
                       url(r'^get_model_ext_valid', views.get_model_ext_valid),
                       url(r'^valid_split', views.valid_split),
                       url(r'^experimental_params', views.experimental_params),
                       url(r'^experimental', views.experimental),
                       url(r'^d_validate', views.choose_dataset_validate),
                       url(r'^exp_design', views.exp_design),
                       url(r'^interlab_substance', views.interlab_select_substance),
                       url(r'^report_delete', views.report_delete),
                       url(r'^reports', views.report_list),
                       url(r'^report', views.report),

                       url(r'^exp_submit', views.exp_submit),
                       url(r'^exp_iter', views.exp_iter),
                       url(r'^interlab_params', views.interlab_params),
                       url(r'^clean_dataset', views.clean_dataset),
                       url(r'^qrf_report', views.qrf_report),
                       url(r'^download_report', views.report_download),
                       url(r'^read_across_dataset', views.read_across_dataset),
                       url(r'^read_across_train', views.read_across_train),
                       url(r'^read_across_predict_model', views.read_across_predict_model),
                       url(r'^read_across_predict', views.read_across_predict),
                       url(r'^factorial_validation', views.factorial_validation),
                       url(r'^factorial_dataset', views.factorial_dataset),
                       url(r'^fact_submit', views.fact_submit),


                       # captcha
                       url(r'^captcha/', include('captcha.urls')),
                       #search
                       (r'^search/', include('haystack.urls')),



                       # Administration page
                       #url(r'^admin/$', 'jaqpot_ui.views.task'),
                       url(r'^admin/', include(admin.site.urls)),



)

jaqpot_ui/models.py
from django.db import models

# Create your models here.

jaqpot_ui/forms.py
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput())
MY_CHOICES = (
    ('Article', 'Article'),
    ('Entry', 'Entry'),
    ('Conference', 'Conference'),
)

class BibtexForm(forms.Form):
        author = forms.CharField(error_messages={'required': 'Please enter author.'})
        abstract = forms.CharField(error_messages={'required': 'Please enter abstract.'})
        title = forms.CharField(error_messages={'required': 'Please enter title.'})
        copyright = forms.CharField(error_messages={'required': 'Please enter copyright.'})
        address = forms.CharField(error_messages={'required': 'Please enter address.'})
        year = forms.CharField(error_messages={'required': 'Please enter year.'})
        pages = forms.CharField(error_messages={'required': 'Please enter number of pages.'})
        volume = forms.CharField( error_messages={'required': 'Please enter volume.'})
        journal = forms.CharField(error_messages={'required': 'Please enter journal.'})
        keyword = forms.CharField(error_messages={'required': 'Please enter keyword.'})
        url = forms.URLField(error_messages={'required': 'Please enter url.'})
        type = forms.ChoiceField(choices=MY_CHOICES)

class FeatureForm(forms.Form):
        feature = forms.CharField()

class TrainForm(forms.Form):
         alg = forms.CharField()

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, error_messages={'required': 'Please enter subject.'}, widget=forms.TextInput(attrs={'placeholder':'Subject'}))
    sender = forms.EmailField(error_messages={'required': 'Please enter your mail'},widget=forms.EmailInput(attrs={'placeholder':'Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows':'3'}), error_messages={'required': 'Please enter your message'})
    captcha = CaptchaField()

class SubstanceownerForm(forms.Form):
        substanceowner = forms.CharField()

class UploadFileForm(forms.Form):
    #title = forms.CharField(max_length=50)
    file = forms.FileField(error_messages={'required': 'Please choose a file.'})
    feature = forms.ChoiceField(widget = forms.Select(), choices=[])

class SelectPmmlForm(forms.Form):
    predicted_feature = forms.ChoiceField(widget = forms.Select(), choices=[])
    pmml = forms.ChoiceField(widget = forms.Select(), choices=[])

class InputForm(forms.Form):
    input = forms.MultipleChoiceField(error_messages={'required': 'Please select input.'}, widget = forms.CheckboxSelectMultiple(), choices=[], required=True)
    input.widget.attrs.update({'class' : "input"})
    output = forms.ChoiceField(error_messages={'required': 'Please select output.'}, widget = forms.RadioSelect(), choices=[], required= True)

class InputFormExpX(forms.Form):
    input = forms.MultipleChoiceField(error_messages={'required': 'Please select input.'}, widget = forms.CheckboxSelectMultiple(), choices=[], required=True)
    input.widget.attrs.update({'class' : "input"})
    output = forms.ChoiceField(widget = forms.RadioSelect(), choices=[], required=False)
    class Meta:
        exclude = ('output',)

class NoPmmlForm(forms.Form):
    pred_feature = forms.ChoiceField(widget = forms.Select(), choices=[])

class TrainingForm(forms.Form):
    scaling = forms.ChoiceField(widget = forms.Select(), choices=[( 'scaling1', 'None' ), ('scaling2', 'Scaling between zero and one'), ('scaling3', 'Normalization')])
    doa = forms.ChoiceField(widget = forms.Select(), choices=[( 'doa1', 'None' ), ('doa2', 'Leverage method') ])
    modelname = forms.CharField(max_length=50, required= True)
    description = forms.CharField(widget=forms.Textarea, required= True)
    description.widget.attrs.update({'style' : "border-radius: 4px;"})
    variables = forms.ChoiceField(error_messages={'required': 'Please select variables.'}, widget = forms.RadioSelect(), choices=[( 'input', 'Select Input variable(s) and endpoint' ), ('pm', 'Select PMML'), ('file', 'Upload PMML file'), ('none', 'Select endpoint only (all other variables will be used as input variables)')])

class ExperimentalForm(forms.Form):
    scaling = forms.ChoiceField(widget = forms.Select(), choices=[( 'scaling1', 'None' ), ('scaling2', 'Scaling between zero and one'), ('scaling3', 'Normalization')])
    variables = forms.ChoiceField(error_messages={'required': 'Please select variables.'}, widget = forms.RadioSelect(), choices=[( 'input', 'Select Input variable(s) and endpoint' ), ('pm', 'Select PMML'), ('file', 'Upload PMML file'), ('none', 'Select endpoint only (all other variables will be used as input variables)')])

class DatasetForm(forms.Form):
    title = forms.CharField(max_length=50, required= True)
    description = forms.CharField(widget=forms.Textarea, required= True)

class ValidationForm(forms.Form):
    #pred_feature = forms.ChoiceField(widget = forms.Select(), choices=[])
    folds = forms.ChoiceField(widget = forms.Select(), choices=[( '3', '3'), ('5', '5'), ('10', '10')])
    stratify = forms.ChoiceField(widget = forms.Select(), choices=[( ' ', 'None'), ('random', 'random'), ('normal', 'normal')])
    variables = forms.ChoiceField(error_messages={'required': 'Please select variables.'}, widget = forms.RadioSelect(), choices=[( 'input', 'Select Input variable(s) and endpoint' ), ('pm', 'Select PMML'), ('file', 'Upload PMML file'), ('none', 'Select endpoint only (all other variables will be used as input variables)')])
    seed = forms.CharField(required=False, error_messages={'required': 'Please enter seed.'},  widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    scaling = forms.ChoiceField(widget = forms.Select(), choices=[( 'scaling1', 'None' ), ('scaling2', 'Scaling between zero and one'), ('scaling3', 'Normalization')])


class ValidationSplitForm(forms.Form):
    scaling = forms.ChoiceField(widget = forms.Select(), choices=[( 'scaling1', 'None' ), ('scaling2', 'Scaling between zero and one'), ('scaling3', 'Normalization')])
    variables = forms.ChoiceField(error_messages={'required': 'Please select variables.'}, widget = forms.RadioSelect(), choices=[( 'input', 'Select Input variable(s) and endpoint' ), ('pm', 'Select PMML'), ('file', 'Upload PMML file'), ('none', 'Select endpoint only (all other variables will be used as input variables)')])
    split_ratio = forms.CharField(required=True, error_messages={'required': 'Please enter split ratio.'},  widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    stratify = forms.ChoiceField(widget = forms.Select(), choices=[(' ', 'None'), ('random', 'random'), ('normal', 'normal')])
    seed = forms.CharField(required=False, error_messages={'required': 'Please enter seed.'},  widget=forms.TextInput(attrs={'style': "margin:5px;"}))

class ExperimentalParamsForm(forms.Form):
    levels = forms.CharField(required=True, error_messages={'required': 'Please enter levels.'},  widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    nVars = forms.CharField(required=True, error_messages={'required': 'Please enter nVars.'}, widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    factors = forms.CharField(required=True, error_messages={'required': 'Please enter factors.'}, widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    varNames = forms.CharField(required=True, error_messages={'required': 'Please enter varNames.'}, widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    nTrials = forms.CharField(required=True, error_messages={'required': 'Please enter nTrials.'}, widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    criterion = forms.CharField(required=True, error_messages={'required': 'Please enter criterion.'}, widget=forms.TextInput(attrs={'style': "margin:5px;"}))
    form = forms.CharField(required=True, error_messages={'required': 'Please enter form.'}, widget=forms.TextInput(attrs={'style': "margin:5px;"}))

class UploadForm(forms.Form):
    #title = forms.CharField(max_length=50)
    file = forms.FileField(error_messages={'required': 'Please choose a file.'})

class InterlabForm(forms.Form):
     modelname = forms.CharField(required=True, error_messages={'required': 'Please enter modelname.'},  widget=forms.TextInput(attrs={'style': "margin:5px;"}))
     description = forms.CharField(required=True, error_messages={'required': 'Please enter description.'},  widget=forms.Textarea(attrs={'cols': 40, 'rows': 4, 'style': "margin:5px;"}))

class ReadAcrossTrainingForm(forms.Form):
    modelname = forms.CharField(max_length=50, required= True)
    description = forms.CharField(widget=forms.Textarea, required= True)
    description.widget.attrs.update({'style' : "border-radius: 4px;"})
    variables = forms.ChoiceField(error_messages={'required': 'Please select variables.'}, widget = forms.RadioSelect(), choices=[( 'input', 'Select Input variable(s) and endpoint' ), ('pm', 'Select PMML'), ('file', 'Upload PMML file'), ('none', 'Select endpoint only (all other variables will be used as input variables)')])

jaqpot_ui/templates/algorithm.html
{% extends "base.html" %}

{% load templates_extras %}

{% block content %}
    <div class="div-table" style="width:100%; display: inline-block;">
    <div style="float:left; width:50%">

        <h3>Regression</h3>
        {% load endless %}
        <div>
             {% paginate 20 regression_alg  %}
             {% for e in regression_alg %}
                <label class="algorithms" style="border: 1px solid #ccc;padding:5px;margin:0 0 5px;display:block; width:99%;">
                    {{e.meta.titles.0}}</label>
            {% endfor %}

            {% get_pages %}
         <div id="pageNavPosition" class="pagination">
             <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for page in pages %}
                        <li>{{page}}</li>
                        {%endfor%}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Next </a>
                            </li>
                        {%endif%}

                   </ul>
                </span>
            </div>
        </div>
    </div>
    <div style="float:left; width:50%">
        <h3>Classification</h3>
        {% load endless %}
        <div>
             {% paginate 20 classification_alg %}
             {% for e in classification_alg %}
                <label class="algorithms" style="border: 1px solid #ccc;padding:5px;margin:0 0 5px;display:block; width:99%;">
                   {{e.meta.titles.0}}</label>
            {% endfor %}

            {% get_pages %}
         <div id="pageNavPosition1" class="pagination">
             <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for other_page in pages %}
                        <li>{{other_page}}</li>
                        {%endfor%}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Next </a>
                            </li>
                        {%endif%}

                   </ul>
                </span>
            </div>
        </div>
    </div>

</div>

{% endblock %}

jaqpot_ui/templates/compound.html
{% extends "base.html" %}

{% block content %}

<div class="div-table" style="width:100%;">
    {% load endless %}
        <div>
             <h1>Compound:</h1>
             {% paginate 20 compound %}
             <div class="list-group">
                {% for c in compound %}
                    <a href="/compound_detail?name={{c.name}}" class="list-group-item">{{c.name}}</a>
                {% endfor %}
             </div>

            {% get_pages %}
         <div id="pageNavPosition" class="pagination">
             <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for page in pages %}
                        <li>{{page}}</li>
                        {%endfor%}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Next </a>
                            </li>
                        {%endif%}

                   </ul>
                </span>
         </div>
        </div>
</div>

{% endblock %}

jaqpot_ui/templates/compound_detail.html
{% extends "base.html" %}

{% block content %}

<div class="div-table" style="width:100%; min-height:650px;">
    <h1>{{name}}</h1>
    </div>
{% endblock %}

jaqpot_ui/templates/explore.html
{% extends "base.html" %}

{% block content %}

<div class="div-table" style="width:100%; display: inline-block;">
    <h1>Explore Chemical Dataset</h1>
    <div style="float:left; width:33%;">
        <h3>Dataset</h3>
        {% load endless %}
        <div>
             {% paginate 20 entries %}
            <ul>
             {% for e in entries %}
               <li><a id="dataset" href="/data_detail?name={{e}}">{{e}}</a></li>
            {% endfor %}
            </ul>

            {% get_pages %}
         <div id="pageNavPosition" class="pagination">
             <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for page in pages %}
                        <li>{{page}}</li>
                        {%endfor%}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Next </a>
                            </li>
                        {%endif%}

                   </ul>
                </span>
            </div>
        </div>
    </div>
    <div style="float:left; width:33%;">
        <h3>Compound</h3>
         <div>
             {% paginate 20 entries_2 using "other_page" %}
             <ul>
             {% for e in entries_2 %}
                 <li><a id="compound" href="/compound_detail?name={{e}}">{{e}}</a></li>
            {% endfor %}
             </ul>
            {% get_pages %}
            <div id="pageNavPosition2" class="pagination">
                <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for other_page in pages %}
                        <li>{{other_page}}</li>
                        {%endfor%}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#"> Next </a>
                            </li>
                        {%endif%}

                   </ul>
                </span>
            </div>
        </div>
    </div>
    <div style="float:left; width:33%;">
       <h3>Conformer</h3>
        <div>
            {% paginate 20 entries_3 using "other_object_page" %}
            <ul>
            {% for e in entries_3 %}
                <li><a id="conformer" href="/compound_detail?name={{e}}">{{e}}</a></li>
            {% endfor %}
            </ul>
            {% get_pages %}
            <div id="pageNavPosition3" class="pagination">
                <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for other_objects_page in pages %}
                        <li>{{other_objects_page}}</li>
                        {%endfor%}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#"> Next </a>
                            </li>
                        {%endif%}

                   </ul>
                </span>
            </div>

        </div>
    </div>
   <!--<a href="/dataset" class="btn btn-success" style="width:10%; float:right; right:10%;" >Save</a> -->
     <input id="choose_alg" type="submit" value="Save" class="btn bt-red" style="width: 10%; float:right; right:10%;">


    <input id="id_alg" style="display:none">
</div>
{% endblock %}

jaqpot_ui/templates/ext_validation.html
{% extends "base.html" %}

{% block content %}

<div class="div-table" style="width:100%;display:inline-block;">
    <h1>Search for models:</h1>
    <div class="form-search search-only" ><i class="search-icon glyphicon glyphicon-search"></i> <input id="filter" class="form-control search-query green-form"></div>
    <div style="width:99%; float:left;">
        <h1>Select a model:</h1>
        {% if error %}
            <h5 style="color:red;">{{error}}</h5>
        {% endif %}
        {% load endless %}
        {% if proposed %}
        <div class="publicdataset list-group">
            <h3>Example models:</h3>
            <p class="list-group-item model" style="background-color:#cf2323; border-color:#cf2323;">Name <span style="float: left; left:20%; position:absolute;">Title</span> <span style="float: left; left:40%; position:absolute;">Description</span> <span style="float: left; left:80%; position:absolute;">Date</span> </p>
            {% for p in proposed %}
                <a href="/external_validation?model={{p.name}}" class="list-group-item model">{{p.name}} <span class="overflow-span" style="float: left; left:20%; position:absolute; width:20%">{{p.meta.titles.0}}</span> <span class="overflow-span" style="float: left; left:40%; position:absolute;width:40%;">{{p.meta.descriptions.0}}</span> <span class="overflow-span" style="float: left; left:80%; position:absolute;width:20%;">{{p.meta.date}}</span>  </a>
            {% endfor %}
            </div>
        {% endif %}
        <div class="publicdataset list-group">
        <h3>All models:</h3>
        {% paginate 20 my_models using "other_objects_page" %}
            <p class="list-group-item model" style="background-color:#cf2323; border-color:#cf2323;">Name <span style="float: left; left:20%; position:absolute;">Title</span> <span style="float: left; left:40%; position:absolute;">Description</span><span style="float: left; left:80%; position:absolute;">Date</span> </p>
        {% for m in my_models %}
            <a href="/external_validation?model={{m.name}}" class="list-group-item model">{{m.name}} <span class="overflow-span" style="float: left; left:20%; position:absolute; width:20%">{{m.meta.titles.0}}</span> <span class="overflow-span" style="float: left; left:40%; position:absolute;width:40%;">{{m.meta.descriptions.0}}</span> <span class="overflow-span" style="float: left; left:80%; position:absolute;width:20%;">{{m.meta.date}}</span> </a>
        {% endfor %}
            </div>
            {% get_pages %}
            <div id="pageNavPosition5" class="pagination">
                <span class="step-links">
                    <ul class="pagination">
                        {% if pages.previous %}
                            <li class="active">
                                {{ pages.previous}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Previous</a>
                            </li>
                        {%endif%}
                        {% for page in pages %}
                        <li>{{page}}</li>
                        {% endfor %}

                        {% if pages.next %}
                            <li class="active">
                                {{ pages.next}}
                            </li>
                        {% else%}
                        <li class="active">
                                <a href="#">Next </a>
                            </li>
                        {%endif%}


                   </ul>
                </span>
            </div>
        </div>
</div>

<script>
    //search the selected model from the list
$(document).ready(function(){
    search("#filter", ".model", "#filter-count");
});
</script>

{% endblock %}

jaqpot_ui/templates/interlab_params.html
{% extends "base.html" %}

{% load templates_extras %}

{% block content %}
<form method="post" id="form1" enctype="multipart/form-data"> {% csrf_token %}
<div class="div-table" style="width:100%; display: inline-block; padding:10px;">
    <a id="back" class="btn bt-red" style="width:3%;" ><i class="glyphicon glyphicon-circle-arrow-left"></i></a>
    <br>

     <h3>Fill in the title and description of the produced model</h3>
        <div>
            <label class="align" >Model name:</label>
            {% if form.modelname.errors %}
               <div class="alert alert-danger" role="alert" style="width: 250px;padding: 5px;">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span>{{form.modelname.errors.as_text}}</span>
               </div>
            {% endif %}
            {{form.modelname}}
        </div>
        <br>
        <p><b>Model description:</b></p>
         {% if form.description.errors %}
               <div class="alert alert-danger" role="alert" style="width: 250px;padding: 5px;">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span>{{form.description.errors.as_text}}</span>
               </div>
            {% endif %}
        {{form.description}}
    <br>
    <input id="choose_params" type="submit" value="Interlab Testing" class="btn bt-red" style="width: 15%; float:left; left:10%;">
    </div>
    </form>
{% endblock %}

jaqpot_ui/templates/login.html
{% extends "base.html" %}

{% block content %}
    <form action="/login/" method="POST"> {% csrf_token %}
		<input type="hidden" name="next" value="{{ next }}" />

        <div class="login">
		<div class="login-screen">
			<div class="app-title">
				<h1>Login</h1>
			</div>

			<div class="login-form">
				{% if error %}
					<div class="alert alert-danger" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span>{{error}}</span>
					</div>
				{% endif %}

				<div class="control-group">
				<!--<input type="text" class="login-field" placeholder="username" id="login-name" name="username" value=""> -->
				<label class="login-field-icon fui-user login-field">{{form.username}}</label>
				</div>

				<div class="control-group">
				<!--<input type="password" class="login-field" value="" placeholder="password" id="login-pass" name="password"> -->
					<label class="login-field-icon fui-lock login-field">{{form.password}}</label>
				<!--<label class="login-field-icon fui-lock" for="login-pass"></label> -->
				</div>
                <input type="submit" class="btn btn-black btn-large btn-block" value="Log in" />
				<!-- <a class="btn btn-black btn-large btn-block" href="/actions">login</a> -->
				<a class="login-link" href="#">Lost your password?</a>
			</div>
		</div>
	</div>

    </form>
{% endblock %}

<script>
$(document).ready(function() {
	$(.fui-user).attr("placeholder", "username");
	$(.fui-lock).attr("placeholder", "password");
	}
</script>